### ISSUE TITLE
Python3 Support

### ISSUE THREAD

**Issue by brookesy2** [srob650/pytvmaze#1]
Howdy,

I modified your library slightly for python3 support. Would love to add it in so I don't have to copy!

https://github.com/brookesy2/pynab/blob/development-postgres/lib/tvmazelib.py

Thanks!

**Comment by srob650** [comment]
Hey,

I'm happy to check it out and support Python 3, can you send a pull request so I can actually see what you've modified more easily?

**Comment by brookesy2** [comment]
For sure! Will do that now :)

I think only a few lines changed.
