### ISSUE TITLE
[BUG] AttributeError: 'Character' object has no attribute '_repr_obj'

### ISSUE THREAD

**Issue by labrys** [srob650/pytvmaze#34]
When attempting to convert a Character to unicode:

```python
>>> import pytvmaze
>>> show = pytvmaze.get_show(maze_id=161, embed='cast')
>>> unicode(show.cast.people[0].character)

Traceback (most recent call last):
  File "<pyshell#18>", line 1, in <module>
    unicode(show.cast.people[0].character)
  File "C:\Python27x64\lib\site-packages\pytvmaze\tvmaze.py", line 255, in __unicode__
    return self._repr_obj(as_unicode=True)
AttributeError: 'Character' object has no attribute '_repr_obj'
```

**Comment by srob650** [comment]
You are trying to coerce a custom class to become a unicode object, which can't be done.  If you are just looking for the name of the character, you can do `show.cast.people[0].character.name` which is already unicode.

**Comment by srob650** [comment]
Looks like that line is leftover from a previous method of python 2/3 support and I must have missed cleaning it up.  That `__unicode__` method should just return `self.name` if you want to change it locally.  I'll put up a fix this week.

**Comment by srob650** [comment]
I saw that, I'm definitely interested to see what you do.  I'm not married to any of this code as long as new code doesn't break anything!

**Comment by labrys** [comment]
The only compatibility thing I believe would be the change to one of the exceptions, as ConnectionError shadows a built-in exception name, however if we subclass both exceptions, even that should still be fine.  Still a lot more to go with it before I consider it done though.  As a side note I'm working on an SQLalchemy based database for it as well.  Ideally it would be a general database for all indexers, but as TV Maze provides a lot of the endpoints we would need I'm using its general structure as the basic template.

**Comment by srob650** [comment]
Very cool.  I'm definitely interested in your project, I have my own personal PVR which is showing its age at this point.  If there's anything I can help with I'm happy to, although my programming skills are that of a hobbyist :p

**Comment by labrys** [comment]
@srob650 one step, if you're interested, a great next step would be to begin adapting this for the other primary indexers such as thetvdb (api v2 preferably), imdb, tmdb, trakt, tvrage (although even though they are back up this would be a really low priority imo as they are now considered unreliable), etc.

**Comment by srob650** [comment]
I consider them pretty unreliable as well.  Let's see where the pieces fall on this API and if we decide to adopt your changes to the master here, then think about that.
