### ISSUE TITLE
[Feature Request] Get information about individual episodes.

### ISSUE THREAD

**Issue by VeNoMouS** [srob650/pytvmaze#37]
Would be nice to request information about nextepisode for example.. I understand that the url is in show.links, but there's no 'native' from within pytvmaze to pull information on said episode, at least that i'm aware of anyway.

**Comment by liiight** [comment]
Just get the episode with another api call

**Comment by VeNoMouS** [comment]
@liiight , is that possible with out doing ```embed='episodes'``` ? I mean there's little point pulling all that information for one episode..

**Comment by liiight** [comment]
Just use one the episode lookup methods

**Comment by VeNoMouS** [comment]
@liiight , yea sorry man, I don't see how... i've looked at every function in there, if i was to manually pull and push that data... whats the point of pushing ...?

Maybe I'm missing something

Lets say for example you want nextepisode...

```
>>> import pytvmaze
>>> show = pytvmaze.get_show(maze_id=43)
>>> show.links
{u'previousepisode': {u'href': u'http://api.tvmaze.com/episodes/633825'}, u'self': {u'href': u'http://api.tvmaze.com/shows/43'}, u'nextepisode': {u'href': u'http://api.tvmaze.com/episodes/637842'}}
>>>
```

you only have the href there... I fail to see how you can do anything from within pytvmaze with only that...

**Comment by liiight** [comment]
Ah i see. I apologize, I completely misunderstood you. Sorry for wasting your time...

**Comment by srob650** [comment]
Yeah unfortunately that is the only info TVMaze provides and they don't currently provide anything in the API to do anything with it.  It's a good point though, I will see if they are willing to add an endpoint for direct episode lookup by TVMaze episode number.

**Comment by VeNoMouS** [comment]
@srob650 , well technically the ahref is a json return, so can always use that :P

**Comment by srob650** [comment]
Oh nice, I've never looked into that.  Well I posted in the forums anyways so we'll see what David says.

**Comment by srob650** [comment]
I suppose we could add properties to the Show class for nextepisode and previousepisode which return a show object based on the links href.  I'll experiment with that in my free time.

**Comment by VeNoMouS** [comment]
@srob650 i already wrote it, if you want it... well just not directly into show...

**Comment by srob650** [comment]
Oh, that's not exactly how I was thinking of it.  I'll happily look at the code but the way I was imagining it is a @property that gets it without needing to know the TVMaze episode id so you can just do this

```
>>> show = pytvmaze.get_show(maze_id=43)
>>> ep = show.next_episode
>>> ep.title
u'La Dame Blanche'
```

**Comment by VeNoMouS** [comment]
yea, im doing that right now, cleaning it up :P was some test code i threw together to test :P

**Comment by srob650** [comment]
Ok cool, do a PR to dev and I'll take a look.  Thanks!

**Comment by VeNoMouS** [comment]
@srob650 PR #38 :)

**Comment by VeNoMouS** [comment]
Ah wait I think I have a small typo there..

```if self.nextepisode is not None and getattr(self.links['previousepisode'],'href',False):```

should not be ```not```

**Comment by srob650** [comment]
You also submitted to master instead of dev

**Comment by VeNoMouS** [comment]
Ah sorry will fix now

**Comment by srob650** [comment]
I should just make dev the default branch.

**Comment by VeNoMouS** [comment]
100th time the charm right? lol PR #40 sent

**Comment by VeNoMouS** [comment]
Ah I just noticed that you didnt quite want it as a function call..

I've got it executing like this atm...
```
>>> import pytvmaze
>>> show = pytvmaze.get_show(maze_id=43)
>>> show.previous_episode()
<Episode(season=02,episode_number=03)>
>>> show.previous_episode().title
u'Useful Occupations and Deceptions'
>>> show.previous_episode().airdate
u'2016-04-23'
```

**Comment by srob650** [comment]
#41
